// Dashboard Data Service
import { getPatients, getVisits } from '../features/shared/dataService';
import { getUsers } from './authService';
import { getExpenses } from '../features/admin/financial-management/financeService';

/**
 * Get dashboard data for Admin
 */
export const getAdminDashboardData = () => {
  const patients = getPatients();
  const allVisits = getVisits(); // Get all visits separately
  const users = getUsers();
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);

  // Filter today's patients
  const patientsToday = patients.filter(p => {
    const createdDate = new Date(p.createdAt);
    return createdDate >= today && createdDate < tomorrow;
  });

  // Filter this month's patients
  const thisMonth = new Date(today.getFullYear(), today.getMonth(), 1);
  const nextMonth = new Date(today.getFullYear(), today.getMonth() + 1, 1);
  const patientsThisMonth = patients.filter(p => {
    const createdDate = new Date(p.createdAt);
    return createdDate >= thisMonth && createdDate < nextMonth;
  });

  // Calculate revenue from PAID visits only
  const calculateRevenueForPeriod = (startDate, endDate) => {
    return allVisits.reduce((sum, visit) => {
      const visitDate = new Date(visit.createdAt);
      const isPaid = visit.paymentStatus === 'paid';
      if (visitDate >= startDate && visitDate < endDate && isPaid) {
        return sum + (visit.finalAmount || visit.totalAmount || 0);
      }
      return sum;
    }, 0);
  };

  // Get REAL expenses from finance service
  const allExpenses = getExpenses();
  const calculateExpensesForPeriod = (startDate, endDate) => {
    return allExpenses.reduce((sum, expense) => {
      const expenseDate = new Date(expense.date);
      if (expenseDate >= startDate && expenseDate < endDate) {
        return sum + expense.amount;
      }
      return sum;
    }, 0);
  };

  const revenueThisMonth = calculateRevenueForPeriod(thisMonth, nextMonth);
  const expensesThisMonth = calculateExpensesForPeriod(thisMonth, nextMonth);
  const profitThisMonth = revenueThisMonth - expensesThisMonth;

  const revenueToday = calculateRevenueForPeriod(today, tomorrow);
  const expensesToday = calculateExpensesForPeriod(today, tomorrow);
  const profitToday = revenueToday - expensesToday;

  // Get last 7 days revenue/expenses - REAL DATA
  const revenue7days = [];
  const expenses7days = [];
  for (let i = 6; i >= 0; i--) {
    const date = new Date(today);
    date.setDate(date.getDate() - i);
    const nextDay = new Date(date);
    nextDay.setDate(nextDay.getDate() + 1);

    const dayRevenue = calculateRevenueForPeriod(date, nextDay);
    const dayExpenses = calculateExpensesForPeriod(date, nextDay);
    
    revenue7days.push({
      date: date.toLocaleDateString('en-US', { weekday: 'short' }),
      value: dayRevenue
    });
    expenses7days.push({
      date: date.toLocaleDateString('en-US', { weekday: 'short' }),
      value: dayExpenses
    });
  }

  // Get staff activity
  const staffUsers = users.filter(u => u.role === 'staff' && u.isActive);
  const staffActivity = staffUsers.map(staff => {
    const staffPatientsToday = patientsToday.filter(p => p.created_by_user_id === staff.userId);
    
    // Count reports generated by this staff today
    const staffReportsToday = allVisits.filter(v => {
      const reportDate = v.reportedAt ? new Date(v.reportedAt) : null;
      return reportDate && reportDate >= today && reportDate < tomorrow && v.result_entered_by_user_id === staff.userId;
    });

    return {
      staffName: staff.fullName,
      patientsHandled: staffPatientsToday.length,
      reportsGenerated: staffReportsToday.length
    };
  });

  // Get today's patients list with ACTUAL status codes from visits
  const patientsListToday = patientsToday.map(patient => {
    // Find latest visit for this patient
    const patientVisits = allVisits.filter(v => v.patientId === patient.patientId);
    let status = 'tests_selected'; // Default status
    let visitId = null;

    if (patientVisits.length > 0) {
      const latestVisit = patientVisits[patientVisits.length - 1];
      visitId = latestVisit.visitId;
      
      // Use ACTUAL visit status codes
      status = latestVisit.status || 'tests_selected';
    }

    return {
      ...patient,
      status,
      visitId
    };
  });

  return {
    patientsToday: patientsToday.length,
    totalPatientsMonth: patientsThisMonth.length,
    revenueMonth: revenueThisMonth,
    profitMonth: profitThisMonth,
    revenueToday,
    expensesToday,
    profitToday,
    patientsListToday,
    staffActivity,
    revenue7days,
    expenses7days
  };
};

/**
 * Get dashboard data for Staff
 */
export const getStaffDashboardData = (userId) => {
  const patients = getPatients();
  const allVisits = getVisits(); // Get all visits separately
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);

  // Filter today's patients
  const patientsToday = patients.filter(p => {
    const createdDate = new Date(p.createdAt);
    return createdDate >= today && createdDate < tomorrow;
  });

  // Filter pending patients (those without results)
  const pendingPatients = allVisits.filter(v => !v.reportedAt);

  // Get today's patients list with ACTUAL status codes from visits
  const patientsListToday = patientsToday.map(patient => {
    // Find latest visit for this patient
    const patientVisits = allVisits.filter(v => v.patientId === patient.patientId);
    let status = 'tests_selected'; // Default status
    let visitId = null;

    if (patientVisits.length > 0) {
      const latestVisit = patientVisits[patientVisits.length - 1];
      visitId = latestVisit.visitId;
      
      // Use ACTUAL visit status codes
      status = latestVisit.status || 'tests_selected';
    }

    return {
      ...patient,
      status,
      visitId
    };
  });

  return {
    patientsToday: patientsToday.length,
    pendingPatients: pendingPatients.length,
    patientsListToday
  };
};
